### ISSUE TITLE
version 2.8 is not available in the registry

### ISSUE THREAD

**Issue by greensopinion** [MatthewVance/testssl-docker#5]
Version 2.8 appears to not be published:

```
$ docker pull mvance/testssl:2.8
Error response from daemon: manifest for mvance/testssl:2.8 not found
$ docker pull mvance/testssl:2.6
2.6: Pulling from mvance/testssl
Digest: sha256:6e5f135fba541269f4244d467f9678b48dce17baa091d713d899229e5bd81d40
Status: Image is up to date for mvance/testssl:2.6
```

**Comment by MatthewVance** [comment]
You're correct. The build on Docker Hub [failed](https://hub.docker.com/r/mvance/testssl/builds/bdnbmmrkt8upssj3asalcda/). The error appears to be because the checksum for v2.8rc3.tar.gz didn't match. This should be updated to the none RC version. Also, I need to make a new build for the recently released [2.9.5-1 version](https://github.com/drwetter/testssl.sh/releases/tag/v2.9.5-1).

```bash
curl -sSL https://github.com/drwetter/testssl.sh/archive/v2.8rc3.tar.gz -o testssl.tar.gz
sha1sum -c -
echo fd33400c580855136644b3300efc79ad53b80d3f *testssl.tar.gz
sha1sum: WARNING: 1 computed checksum did NOT match
testssl.tar.gz: FAILED
```

**Comment by rainabba** [comment]
I just hit the same so I guess this project is abandoned.

**Comment by MatthewVance** [comment]
My apologies. This is semi abandoned. I had hoped to resume some
maintenance once I had a bit more free time. I have been without Internet
access at home for a couple of weeks until yesterday so I couldn't even
push a build to the repo to resolve the earlier reported issue.

Short term workaround is to build the Dockerfile locally. That's probably
best anyway as I've been having trouble with the auto builds on Docker Hub
not finishing correctly.

**Comment by greensopinion** [comment]
No problem @MatthewVance!  

It looks like there's now an "official" testssl.sh Dockerfile available from here: https://github.com/drwetter/testssl.sh
We've been using this successfully now for a few months, apologies for not updating you here.

**Comment by MatthewVance** [comment]
No worries. I had talked to @drwetter about taking the link to this repo off his site since I haven't had time to maintain this. Knowing there is an official version now, I may mark this project as no longer maintained.
