### ISSUE TITLE
Add 2.9.5

### ISSUE THREAD

**Issue by drwetter** [MatthewVance/testssl-docker#6]
Hello @MatthewVance ,

could you add the release 2.9.5 please? There should be not point keeping any older version as 2.8. I am deprecating 2.8 on the master repository, other releases have a pure historical value,

Cheers, Dirk

**Comment by MatthewVance** [comment]
Hi Dirk,

I would like to add support for 2.9.5 and don’t think it would be difficult
to implement, but have not had time between my full time job and working on
a Master’s degree. To further complicate matters, my machine where I mange
and test this repo is currently down (I think it’s a PSU problem).

It may be best to pull the reference to my repo from the README until I’m
better able to support this Docker image. I can also take down the repo
from GitHub if needed.

**Comment by drwetter** [comment]
Hi Matt,

thanks for the prompt and honest reply. I opted for the removal. Let me know if you're done with your degree and your PSU. Good luck!

     Dirk

**Comment by MatthewVance** [comment]
I understand and wish it’s was where I could help more at the moment
because I appreciate what you’re doing with TestSSL.

**Comment by greensopinion** [comment]
@MatthewVance what's required to add 2.9.5?  We might be interested in contributing, but it's not clear what needs to be done.

**Comment by MatthewVance** [comment]
Thank you @greensopinion. That would be great. I recommend the following:

- Create New Folder for 2.9.5 with a Dockerfile based on the 2.8rc3 one. 
- Update the Dockerfile to install the new version by updating TESTSSL_DOWNLOAD_URL and TESTSSL_DOWNLOAD_SHA1 variables. 
- Check to see if the PeterMosmans/openssl library used by talso needs to be updated. 
- Build the Dockerfile locally (docker build -t mvance/testssl:2.9.5 . > testssl-build.log). 
- Test and submit pull request when ready.

**Comment by naerymdan** [comment]
Pull request: https://github.com/MatthewVance/testssl-docker/pull/7

**Comment by MatthewVance** [comment]
@naerymdan Thanks!

**Comment by greensopinion** [comment]
Fantastic!  Thanks @naerymdan
